# Generated by Django 5.2.3 on 2025-11-07 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Väri',
                'verbose_name_plural': 'Värit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Varasto', max_length=20)),
            ],
            options={
                'verbose_name': 'Varasto',
                'verbose_name_plural': 'Varastot',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_workstation', models.CharField(default='', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Työpiste',
                'verbose_name_plural': 'Työpisteet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_ordered', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koodi', models.CharField(max_length=50)),
                ('nimike', models.CharField(blank=True, default=' - ', max_length=100, null=True)),
                ('category', models.CharField(choices=[('integraalit', 'Integraalit'), ('elastomeerit', 'Elastomeerit'), ('kovat', 'Kovat')], default='integraalit', max_length=50)),
                ('is_frequently_used', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.color')),
            ],
            options={
                'verbose_name': 'Tuote',
                'verbose_name_plural': 'Tuotteet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Odottaa'), ('processing', 'Käsitelyssä'), ('delivered', 'Toimitettu')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tilaus',
                'verbose_name_plural': 'Tilaukset',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.color')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.warehouse')),
            ],
            options={
                'verbose_name': 'Varaston tuote',
                'verbose_name_plural': 'Varaston tuotteet',
            },
        ),
        migrations.AddField(
            model_name='warehouse',
            name='items',
            field=models.ManyToManyField(through='stock.WarehouseItem', to='stock.item'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('comment', models.TextField(blank=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.cart')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.color')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.item')),
                ('workstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.workstation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('koodi', 'color'), name='unique_item_code_name'),
        ),
        migrations.AddConstraint(
            model_name='warehouseitem',
            constraint=models.UniqueConstraint(fields=('warehouse', 'item', 'color'), name='unique_warehouse_item_color'),
        ),
    ]
