# Generated by Django 5.2.3 on 2025-11-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_frequently_used',
        ),
        migrations.RemoveField(
            model_name='item',
            name='usage_count',
        ),
    ]
