# Generated by Django 5.2 on 2025-04-16 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fistname',
            new_name='firstname',
        ),
    ]
