# Generated by Django 5.2 on 2025-04-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_rename_fistname_user_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desknumber',
            field=models.IntegerField(null=True),
        ),
    ]
