# Generated by Django 5.2.3 on 2025-06-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_cartitem_color_cartitem_workstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('integraalit', 'Integraalit'), ('elastomeerit', 'Elastomeerit'), ('kovat', 'Kovat')], default='integraalit', max_length=100),
        ),
    ]
