# Generated by Django 5.2.3 on 2025-06-23 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_item_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='status',
            new_name='category',
        ),
    ]
