# Generated by Django 5.2.3 on 2025-06-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_rename_status_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Odottaa'), ('processing', 'Käsitelyssä'), ('delivered', 'Toimitettu')], default='pending', max_length=20),
        ),
    ]
