# Generated by Django 5.2.3 on 2025-08-11 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.color'),
        ),
    ]
