# Generated by Django 5.2.3 on 2025-08-11 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_item_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehouseitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='warehouseitem',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.color'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouseitem',
            unique_together={('warehouse', 'item', 'color')},
        ),
    ]
