# Generated by Django 5.2.3 on 2025-08-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_warehouseitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('integraalit', 'Integraalit'), ('elastomeerit', 'Elastomeerit'), ('kovat', 'Kovat')], default='integraalit', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='koodi',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='nimike',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(default='Varasto', max_length=20),
        ),
    ]
