# Generated by Django 5.2 on 2025-06-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_remove_order_completed_remove_order_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Odottaa'), ('delivered', 'Toimitettu')], default='pending', max_length=20),
        ),
    ]
