# Generated by Django 5.2.3 on 2025-08-20 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_alter_color_color_alter_item_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
    ]
