# Generated by Django 5.2.3 on 2025-06-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='saldo',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='coment',
            field=models.TextField(blank=True),
        ),
    ]
