# Generated by Django 5.2.3 on 2025-09-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_remove_item_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
