# Generated by Django 5.2.3 on 2025-06-13 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_remove_item_saldo_cartitem_coment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='coment',
            new_name='comment',
        ),
    ]
