# Generated by Django 5.2.3 on 2025-06-13 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_rename_coment_cartitem_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Основной склад', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='koodi',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='lisanimike',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.warehouse')),
            ],
            options={
                'unique_together': {('warehouse', 'item')},
            },
        ),
        migrations.AddField(
            model_name='warehouse',
            name='items',
            field=models.ManyToManyField(through='stock.WarehouseItem', to='stock.item'),
        ),
    ]
