# Generated by Django 5.2.3 on 2025-10-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_alter_warehouseitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='nimike',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
