# Generated by Django 5.2.3 on 2025-06-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_warehouse_alter_item_koodi_alter_item_lisanimike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(default='Varasto', max_length=100),
        ),
    ]
