# Generated by Django 5.2.3 on 2025-10-24 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_alter_item_nimike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouseitem',
            options={'verbose_name': 'Varaston tuote', 'verbose_name_plural': 'Varaston tuotteet'},
        ),
    ]
