# Generated by Django 5.2.3 on 2025-10-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_alter_warehouseitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'managed': True, 'verbose_name': 'Väri', 'verbose_name_plural': 'Värit'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'managed': True, 'verbose_name': 'Tuote', 'verbose_name_plural': 'Tuotteet'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'managed': True, 'verbose_name': 'Tilaus', 'verbose_name_plural': 'Tilaukset'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'managed': True, 'verbose_name': 'Varasto', 'verbose_name_plural': 'Varastot'},
        ),
        migrations.AlterModelOptions(
            name='workstation',
            options={'managed': True, 'verbose_name': 'Työpiste', 'verbose_name_plural': 'Työpisteet'},
        ),
    ]
