# Generated by Django 5.2.3 on 2025-10-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_alter_color_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='koodi',
            field=models.CharField(max_length=50),
        ),
    ]
