# Generated by Django 5.2.3 on 2025-10-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_alter_item_nimike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='nimike',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
    ]
