# Generated by Django 5.2.3 on 2025-10-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_alter_item_nimike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': 'Tilaus', 'verbose_name_plural': 'Tilaukset'},
        ),
    ]
